
```{r}
packages = c("corrplot","ggpubr","GGally","tidyverse")
for (p in packages) {
  # 'require' checks whether package exists and returns TRUE or FALSE
  if (!require(p, character.only = T)) {
    install.packages(p)
  }
  library(p, character.only = T)
}
setwd('/Users/runyuwang/Google Drive/Visual Analytics/Assignment/Assignment Workspace/')

all_bird_file = 'all_birds_wav.csv'
test_bird_file = 'test_birds_from_kasios_wav.csv'
```

Load all bird file and test bird file
```{r}
all_bird_data = read_csv(all_bird_file)
test_bird_data = read_csv(test_bird_file) 
```

EDA and Remove NA
```{r}
#drop columns with NA value
drops = c('pitchCep_mean', 'pitchCep_median', 'pitchCep_sd')
all_bird_data = all_bird_data[,!names(all_bird_data) %in% drops]
test_bird_data = test_bird_data[,!names(test_bird_data) %in% drops]

#count number of NA values per column in all_bird_data
colSums(is.na(all_bird_data))
#explore NA value in each row
df_all = all_bird_data[rowSums(is.na(all_bird_data))>0,]

#count number of NA values per column in test_bird_data
colSums(is.na(test_bird_data))
#explore NA value in each row
test_bird_data[rowSums(is.na(test_bird_data))>0,]



all_bird_data <- na.omit(all_bird_data)
```


```{r}
x = all_bird_data[,15:20]
y = cor(all_bird_data[,15:20])

y[,1]

corrplot(y,method="circle")
```








```{r}
wav_file = readWave("Test Birds from Kasios wav/12.wav")
env(wav_file)
oscillo(wav_file)
str(wav_file)

wav_file_ab = readWave("ALL BIRDS wav/Green-Tipped-Scarlet-Pipit-174547.wav")
env(wav_file_ab)
oscillo(wav_file_ab)
```

